var emp = [1, "Ram"];
console.log(emp[0]);
console.log(emp[1]);
var emp1 = [1, "Ram", false];
console.log(emp1[0]);
console.log(emp1[1]);
console.log(emp1[2]);
var emp2 = [1, "Sam"];
emp2.push(2, "Raj");
console.log(emp2);
var emp3;
emp3 = [[1, "Ram"], [2, "Sam"], [3, "Raj"]];
console.log(emp3[0][0]);
console.log(emp3[0][1]);
